"""
This type stub file was generated by pyright.
"""

from yagmail.error import YagAddressError, YagConnectionClosed
from yagmail.password import register
from yagmail.sender import SMTP, logging
from yagmail.utils import inline, raw

__project__ = ...
__version__ = ...
