"""
This type stub file was generated by pyright.
"""

def register(username, password): # -> None:
    """ Use this to add a new gmail account to your OS' keyring so it can be used in yagmail """
    ...

def main(): # -> None:
    """ This is the function that is run from commandline with `yagmail` """
    ...

