"""
This type stub file was generated by pyright.
"""

def resolve_addresses(user, useralias, to, cc, bcc): # -> dict[str, list[Any]]:
    """ Handle the targets addresses, adding aliases when defined """
    ...

def make_addr_alias_user(email_addr): # -> tuple[Any, Any]:
    ...

def make_addr_alias_target(x, addresses, which): # -> None:
    ...

def add_subject(msg, subject): # -> None:
    ...

def add_recipients_headers(user, useralias, msg, addresses): # -> None:
    ...

def add_message_id(msg, message_id=..., group_messages=...): # -> None:
    ...

