"""
This type stub file was generated by pyright.
"""

PY3 = ...
def dt_converter(o): # -> str | None:
    ...

def serialize_object(content): # -> tuple[bool, str | Any]:
    ...

def prepare_message(user, useralias, addresses, subject, contents, attachments, headers, encoding, prettify_html=..., message_id=..., group_messages=..., dkim=...):
    """Prepare a MIME message"""
    ...

def prepare_contents(contents, encoding): # -> tuple[bool, list[Any]]:
    ...

def get_mime_object(is_marked_up, content_string, encoding): # -> dict[str, Any | None]:
    ...

