"""
This type stub file was generated by pyright.
"""

"""
Adapted from:
http://blog.macuyiko.com/post/2016/how-to-send-html-mails-with-oauth2-and-gmail-in-python.html

1. Generate and authorize an OAuth2 (generate_oauth2_token)
2. Generate a new access tokens using a refresh token(refresh_token)
3. Generate an OAuth2 string to use for login (access_token)
"""
input = ...
GOOGLE_ACCOUNTS_BASE_URL = ...
REDIRECT_URI = ...
def command_to_url(command): # -> LiteralString:
    ...

def url_format_params(params): # -> LiteralString:
    ...

def generate_permission_url(client_id): # -> LiteralString:
    ...

def call_authorize_tokens(client_id, client_secret, authorization_code): # -> Any:
    ...

def call_refresh_token(client_id, client_secret, refresh_token): # -> Any:
    ...

def generate_oauth2_string(username, access_token, as_base64=...): # -> str | LiteralString:
    ...

def get_authorization(google_client_id, google_client_secret): # -> tuple[Any, Any, Any]:
    ...

def refresh_authorization(google_client_id, google_client_secret, google_refresh_token): # -> tuple[Any, Any]:
    ...

def get_oauth_string(user, oauth2_info): # -> str | LiteralString:
    ...

def get_oauth2_info(oauth2_file: str, email_addr: str): # -> Any | dict[str, Any | str]:
    ...

