"""
This type stub file was generated by pyright.
"""

def handle_password(user, password): # -> str:
    """ Handles getting the password"""
    ...

def register(username, password): # -> None:
    """ Use this to add a new gmail account to your OS' keyring so it can be used in yagmail """
    ...

