"""
This type stub file was generated by pyright.
"""

class raw(str):
    """ Ensure that a string is treated as text and will not receive 'magic'. """
    ...


class inline(str):
    """ Only needed when wanting to inline an image rather than attach it """
    ...


def find_user_home_path(): # -> str:
    ...

